---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
  - name: grpc
    port: 9555
    targetPort: grpc
---