---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: frontend
  namespace: default
spec:
  host: aes-labs.com
  prefix: /
  service: frontend:80
  labels:
    ambassador:
      - request_label_group:
        - 5rpm
---
